// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// This a placeholder for typescript. The real files are generated by scripts/environment.js.
export declare const THEME: string;
export declare const PACKAGE_SOURCE: string;
export declare const PACKAGE_VERSION: string;
/** Indicates that the current theme is always in visual refresh mode. */
export declare const ALWAYS_VISUAL_REFRESH: boolean;
