# This workflow executes a dry-run build, which includes building and testing all dependent @cloudscape-design packages in GitHub.
# This ensures that the changes in the current package do not cause any regressions for its consumers.
name: Dry-run
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  merge_group:

jobs:
  buildBoardComponents:
    name: Build board components
    runs-on: ubuntu-latest
    steps:
      - uses: cloudscape-design/actions/.github/actions/build-repository@main
        with:
          repository: cloudscape-design/board-components

  buildDemos:
    name: Build demos
    runs-on: ubuntu-latest
    needs:
      - buildBoardComponents
    steps:
      - name: Build
        uses: cloudscape-design/actions/.github/actions/build-repository@main
        with:
          repository: cloudscape-design/demos
