# This workflow releases the current package to a dedicated private CodeArtifact repository.
# One repository may publish more than one package. For more details refer to the release-package Action.
name: Release

on:
  push:
    branches:
      - main
      - "dev-v3-*"

permissions:
  id-token: write
  contents: read

jobs:
  release:
    uses: cloudscape-design/actions/.github/workflows/release.yml@auto-remove-scripts-testing
    secrets: inherit
    with:
      publish-packages: lib/components,lib/components-themeable
