name: Visual Regressions

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  visual-regression:
    uses: cloudscape-design/actions/.github/workflows/visual-regression.yml@main
    with:
      repository: ${{ github.repository }}
    secrets: inherit
